version: '3'
services:
  portainer:
    entrypoint: /portainer --host unix:///var/run/docker.sock --no-auth
    # Use develop branch until https://github.com/portainer/portainer/issues/2279 is released.
    image: portainer/portainer:develop
    ports:
      - "0.0.0.0:5001:9000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_DATA_DIR}:/data
  file_manager:
    image: astroswarm/file_manager:latest
    environment:
      SHARED_DIR: ${SHARED_DIR}
    ports:
      - "5002:8080"
    restart: unless-stopped
    volumes:
      - ${SHARED_DIR}:/mnt/shared
  localtunnel:
    depends_on:
      - brain
    environment:
      HTTP_HOST: brain
      HTTP_PORT: 9292
    image: astroswarm/localtunnel_client:latest
    restart: unless-stopped
  heartbeat:
    build:
      context: ./heartbeat
    image: "astroswarm/heartbeat-${ARCH}:latest"
    depends_on:
      - brain
    environment:
      BRAIN_WAN_PORT: 5003
      HEARTBEAT_INTERVAL_IN_SECONDS: 5
      HOST_DATA_DIR: /host-data
    restart: unless-stopped
    volumes:
      - ${HOST_DATA_DIR}:/host-data:ro
  brain:
    build:
      context: ./brain
      args:
        BRAIN_GO_VERSION: "1.10" # Without quotes, this gets interpreted as float 1.1
        BRAIN_GO_ARCH: ${BRAIN_GO_ARCH}
    image: "astroswarm/brain-${ARCH}:latest"
    command: rbenv exec bundle exec rackup -s puma -p 9292 -o 0.0.0.0 -E development
    environment:
      # Get gateway address on container via: ip route show | awk '/^default/ {print $3}'
      ASTROSWARM_API_HOST: ${ASTROSWARM_API_HOST}
      HOST_DATA_DIR: /host-data
      PASTEBINIT_USERNAME: ${PASTEBINIT_USERNAME}
      PASTEBINIT_PASS: ${PASTEBINIT_PASS}
      PASTEBINIT_URI: ${PASTEBINIT_URI}
      RACK_ENV: ${RACK_ENV}
    restart: unless-stopped
    volumes:
      - ${SYSLOG_PATH}:/mnt/host/var/log/syslog:ro
      - ${WPA_SUPPLICANT_PATH}:/mnt/host/etc/wpa_supplicant/wpa_supplicant.conf
      - ${ETH_ADDRESS_FILE}:/mnt/host/sys/class/net/eth0/address
      - ${HOST_DATA_DIR}:/host-data:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHARED_DIR}:/mnt/shared
    ports:
      - "5003:9292"
  frontend:
    build:
      context: ./frontend
      dockerfile: "${FRONTEND_DOCKERFILE}"
    image: "astroswarm/frontend-${ARCH}:latest"
    ports:
      - "5000:80"   # HTTP server
    restart: unless-stopped
