version: '3'
services:
  portainer:
    entrypoint: /portainer --host unix:///var/run/docker.sock --no-auth
    image: portainer/portainer
    ports:
      - "5001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  heartbeat:
    build:
      args:
        ARCH: x86_64
      context: ./heartbeat
      dockerfile: Dockerfile
    environment:
      BRAIN_WAN_PORT: 5000
      HEARTBEAT_INTERVAL_IN_SECONDS: 5
      HOST_DATA_DIR: /host-data
    depends_on:
      - swarm_brain
    volumes:
      - ./host-data:/host-data:ro
  swarm_brain:
    build:
      args:
        ARCH: x86_64
      context: ./swarm_brain
      dockerfile: Dockerfile
    command: rbenv exec bundle exec rackup -s puma -p 9292 -o 0.0.0.0 -E development
    environment:
      # Get gateway address on container via: ip route show | awk '/^default/ {print $3}'
      ASTROSWARM_API_HOST: 172.19.0.1:3001
      HOST_DATA_DIR: /host-data
      RACK_ENV: development
    volumes:
      - ./host-data:/host-data:ro
      - ./swarm_brain:/app
      - bundle:/bundle
    ports:
      - "5000:9292"
volumes:
  bundle:
