version: '3'
services:
  portainer:
    entrypoint: /portainer --host unix:///var/run/docker.sock --no-auth
    image: portainer/portainer
    ports:
      - "0.0.0.0:5001:9000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_DATA_DIR}:/data
  file_manager:
    build:
      context: https://github.com/astroswarm/file_manager.git
    environment:
      SHARED_DIR: ${SHARED_DIR}
    ports:
      - "5002:8080"
    restart: unless-stopped
    volumes:
      - ${SHARED_DIR}:/mnt/shared
  localtunnel:
    depends_on:
      - brain
    environment:
      HTTP_HOST: brain
      HTTP_PORT: 9292
    image: astroswarm/localtunnel_client:latest
    restart: unless-stopped
  heartbeat:
    build:
      context: ${HEARTBEAT_CONTEXT}
    depends_on:
      - brain
    environment:
      BRAIN_WAN_PORT: 5000
      HEARTBEAT_INTERVAL_IN_SECONDS: 5
      HOST_DATA_DIR: /host-data
    volumes:
      - ${HOST_DATA_DIR}:/host-data:ro
  brain:
    build:
      context: ${BRAIN_CONTEXT}
    command: rbenv exec bundle exec rackup -s puma -p 9292 -o 0.0.0.0 -E development
    environment:
      # Get gateway address on container via: ip route show | awk '/^default/ {print $3}'
      ASTROSWARM_API_HOST: ${ASTROSWARM_API_HOST}
      HOST_DATA_DIR: /host-data
      RACK_ENV: ${RACK_ENV}
    volumes:
      - ${SYSLOG_PATH}:/mnt/host/var/log/syslog:ro
      - ${HOST_DATA_DIR}:/host-data:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHARED_DIR}:/mnt/shared
    ports:
      - "5000:9292"
