version: '3'
services:
  heartbeat:
    build:
      context: ./heartbeat
      dockerfile: Dockerfile.development
    environment:
      BRAIN_HOST: swarm_brain:9292
      HEARTBEAT_INTERVAL_IN_SECONDS: 30
    depends_on:
      - swarm_brain
  swarm_brain:
    build:
      context: ./swarm_brain
      dockerfile: Dockerfile.development
    command: rbenv exec bundle exec rackup -s puma -p 9292 -o 0.0.0.0 -E development
    environment:
      # Get gateway address on container via: ip route show | awk '/^default/ {print $3}'
      ASTROSWARM_API_HOST: 172.19.0.1:3001
      HOST_DATA_DIR: /host-data
      RACK_ENV: development
    volumes:
      - ./mock-host-data:/host-data:ro
      - ./swarm_brain:/app
      - bundle:/bundle
    ports:
      - "5000:9292"
volumes:
  bundle:
